#!/usr/bin/env node
/*
 * Run the whole site locally, gate and all.
 *
 *   node tools/serve-local.js
 *
 * A plain static server (vite, http-server, `python3 -m http.server`) will
 * happily serve web/ — but it won't run deploy/edge-auth.js, so you'd be
 * looking at the old, ungated site. This puts the real edge function in front
 * of the real files: it loads edge-auth.js into a stub of the CloudFront
 * runtime, turns each incoming request into a CloudFront event, and either
 * serves the file or returns whatever response the function decided on.
 *
 * So passes, redeeming, expiry, roles and minting all behave as they will in
 * production. What it can NOT tell you is whether the deployment works — the
 * 10 KB and 1 ms limits, and whether the runtime really offers
 * crypto.createHmac. deploy/publish-auth.sh checks those against CloudFront
 * itself, in its sandbox, before it publishes anything.
 *
 * No AWS account or bucket access needed.
 */
'use strict';
const http = require('http');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const WEB = path.join(ROOT, 'web');
const PORT = Number((process.argv.find((a) => a.startsWith('--port=')) || '').split('=')[1]) || 8080;

/* Fixed, so a pass still works after you restart the server — and so it is
   obvious in a stack trace that this is not a real key. Production keys are
   generated by publish-auth.sh and kept in SSM. */
const DEV_SECRET = 'local-development-only-not-a-real-key';

// ---------------------------------------------------------------- the edge
const src = fs.readFileSync(path.join(ROOT, 'deploy', 'edge-auth.js'), 'utf8');
if (!src.includes('REPLACE_AT_DEPLOY')) {
  console.error('edge-auth.js has a key baked into it — refusing to run. Restore the placeholder.');
  process.exit(1);
}
const ctx = {
  require: (m) => { if (m === 'crypto') return crypto; throw new Error('no module ' + m); },
  Date, JSON, Math, String, parseInt, decodeURIComponent, console,
};
vm.createContext(ctx);
vm.runInContext(src.replace('REPLACE_AT_DEPLOY', DEV_SECRET) + '\nthis.__api={handler,issue};', ctx);
const { handler, issue } = ctx.__api;

// ------------------------------------------------------------ static files
const MIME = {
  '.html': 'text/html; charset=utf-8', '.json': 'application/json',
  '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.webp': 'image/webp', '.pdf': 'application/pdf',
  '.ico': 'image/x-icon',
};

/* index.html is wired to the live CloudFront distribution, so left alone the
   page would fetch the catalogue straight past this server — and past the
   gate. Point it back at the copy we're serving. */
function localise(html) {
  return html
    .replace(/var IMAGE_BASE = "[^"]*";/, 'var IMAGE_BASE = "";              /* localised by serve-local.js */')
    .replace(/var CATALOGUE_URL = "[^"]*";/, 'var CATALOGUE_URL = "";           /* localised by serve-local.js */');
}

function serveFile(uri, res) {
  const rel = uri === '/' ? '/index.html' : uri;
  const file = path.join(WEB, path.normalize(decodeURIComponent(rel)).replace(/^(\.\.[/\\])+/, ''));
  if (!file.startsWith(WEB)) { res.writeHead(403).end('no'); return; }

  fs.readFile(file, (err, buf) => {
    if (err) {
      res.writeHead(404, { 'content-type': 'text/html; charset=utf-8' });
      res.end('<h1>404</h1><p>No <code>' + rel + '</code> in web/.<p>' +
        (/\.(jpe?g|png|pdf|gif|webp)$/i.test(rel)
          ? 'Scans live in the S3 bucket, not the repo — placeholders are expected here.'
          : ''));
      return;
    }
    const ext = path.extname(file).toLowerCase();
    let body = buf;
    if (rel === '/index.html') body = Buffer.from(localise(buf.toString('utf8')), 'utf8');
    res.writeHead(200, { 'content-type': MIME[ext] || 'application/octet-stream', 'cache-control': 'no-store' });
    res.end(body);
  });
}

// ------------------------------------------------- node request <-> event
function toEvent(req) {
  const u = new URL(req.url, 'http://' + (req.headers.host || 'localhost'));
  const querystring = {};
  for (const [k, v] of u.searchParams) querystring[k] = { value: v };

  const cookies = {};
  for (const part of (req.headers.cookie || '').split(';')) {
    const i = part.indexOf('=');
    if (i > 0) cookies[part.slice(0, i).trim()] = { value: part.slice(i + 1).trim() };
  }

  const headers = {};
  for (const [k, v] of Object.entries(req.headers)) {
    if (typeof v === 'string') headers[k.toLowerCase()] = { value: v };
  }
  return { version: '1.0', context: { eventType: 'viewer-request' },
    request: { method: req.method, uri: u.pathname, querystring, headers, cookies } };
}

function sendResponse(out, res) {
  const headers = {};
  for (const [k, v] of Object.entries(out.headers || {})) headers[k] = v.value;

  const setCookie = [];
  for (const [name, c] of Object.entries(out.cookies || {})) {
    // Secure cookies are accepted on http://localhost by Chrome and Firefox
    // (localhost counts as a secure context). Safari is stricter — pass
    // --insecure-cookie if you need to test there.
    let attrs = c.attributes || '';
    if (process.argv.includes('--insecure-cookie')) attrs = attrs.replace(/;?\s*Secure/i, '');
    setCookie.push(name + '=' + c.value + (attrs ? '; ' + attrs : ''));
  }
  if (setCookie.length) headers['set-cookie'] = setCookie;

  let body = out.body ? out.body.data : '';
  // The function builds absolute https:// links from the Host header, which is
  // right in production and wrong on localhost.
  if (body) body = body.replace(/https:\/\/(localhost|127\.0\.0\.1)(:\d+)?/g, 'http://$1$2');

  res.writeHead(out.statusCode || 200, headers);
  res.end(body);
}

// ------------------------------------------------------------------ serve
const server = http.createServer((req, res) => {
  let out;
  try {
    out = handler(toEvent(req));
  } catch (e) {
    res.writeHead(500, { 'content-type': 'text/plain' });
    res.end('edge-auth.js threw: ' + e.message + '\n' + e.stack);
    return;
  }
  const passed = out && typeof out.uri === 'string';
  console.log('  ' + (passed ? 'pass ' : String(out.statusCode || '???').padEnd(5)) + ' ' + req.url.slice(0, 90));
  if (passed) serveFile(out.uri, res); else sendResponse(out, res);
});

server.listen(PORT, () => {
  const admin = issue('you@example.org', '1');
  const reader = issue('reader@example.org', '3');
  const base = 'http://localhost:' + PORT;
  console.log(`
  Talyllyn archive — local run, with the real access gate in front.

    ${base}/                     turned away, as a stranger would be

  Let yourself in as an administrator (this also opens /admin.html,
  where you can mint further passes):

    ${base}/access?t=${admin.token}

  Or as an ordinary reader on a one-day pass:

    ${base}/access?t=${reader.token}

  Signed with a fixed development key, so these keep working across
  restarts. Scans aren't in the repo, so images show as placeholders.
  Ctrl-C to stop.
`);
});
